api_platform:
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_client_enabled: false
        pagination_client_items_per_page: true
    collection:
        pagination:
            enabled_parameter_name: pagination