framework:
    messenger:
        buses:
            command.bus:
                middleware:
                    - App\Messenger\Middleware\UnwrapExceptionMiddleware
                    - validation
                    - doctrine_transaction
        transports:
            async-high:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        async-high:
                            binding_keys: [async-high]
                retry_strategy:
                    max_retries: 1
            async-medium:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        async-medium:
                            binding_keys: [async-medium]
                retry_strategy:
                    max_retries: 1
            async-low:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        async-low:
                            binding_keys: [async-low]
                retry_strategy:
                    max_retries: 1
            sync: "sync://"

        routing:
            App\Application\Command\CreateGasCurrentPrice: sync
            App\Application\Command\CreateGasPriceHistory: sync

            App\Application\Command\CreateOrUpdateGasStation: async-high
            App\Application\Command\CreateOrUpdateGasPrice: async-medium
